name: gossip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: build
      run: go build

    - name: test
      run: go test ./...
    
    - name: race
      run: go test ./... -race

  irctest:
    runs-on: ubuntu-latest
    steps:
    - name: checkout gossip
      uses: actions/checkout@v4
      with:
        path: gossip

    - name: checkout irctest
      uses: actions/checkout@v4
      with:
        repository: progval/irctest
        path: irctest
    
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: irctest
      run: |
        export PATH="$(pwd)/gossip/:$PATH"

        cd gossip
        go build
        cd ..

        cd irctest
        pip3 install -r requirements.txt
        PYTHONPATH=../gossip/ pytest --controller gossip -k 'not Ergo and not deprecated and not strict and not testListCreationTime and not testListTopicTime'
  
  parser-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout gossip
      uses: actions/checkout@v4
      with:
        path: gossip

    - name: checkout parser-tests
      uses: actions/checkout@v4
      with:
        repository: ircdocs/parser-tests
        path: parser-tests

    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: parser-tests
      run: |
        cd gossip
        go test ./scan/msg/ ./scan/wild -tags ext_vectors

